# pixels-spark specific defaults.
# Copy this file to $PIXELS_HOME/etc/pixels-spark.properties and adjust values there.

pixels.spark.rpc.host=localhost
pixels.spark.rpc.port=9091
pixels.spark.metadata.host=localhost
pixels.spark.metadata.port=18888
pixels.spark.delta.auto-create=true
pixels.spark.delta.delete.mode=hard
pixels.spark.delta.trigger.mode=once
pixels.spark.delta.trigger.interval=0 seconds
pixels.spark.delta.hash-bucket.count=0
