# pixels-spark config for local CDC to HyBench sf10

pixels.spark.rpc.host=127.0.0.1
pixels.spark.rpc.port=9091
pixels.spark.metadata.host=127.0.0.1
pixels.spark.metadata.port=18888
pixels.spark.master=local[2]

pixels.spark.delta.target.path=s3a://home-zinuo/deltalake/hybench_sf10
pixels.spark.delta.auto-create=true
pixels.spark.delta.delete.mode=hard
pixels.spark.delta.trigger.mode=processing-time
pixels.spark.delta.trigger.interval=10 seconds
pixels.spark.delta.hash-bucket.count=16
