tables=warehouse,district,customer,history,neworder,order,orderline,item,stock,nation,supplier,region

table.warehouse.file=WAREHOUSE.tbl
table.warehouse.delimiter=|
table.warehouse.primary-keys=w_id
table.warehouse.schema=w_id:int,w_name:string,w_street_1:string,w_street_2:string,w_city:string,w_state:string,w_zip:string,w_tax:float,w_ytd:float,freshness_ts:timestamp

table.district.file=DISTRICT.tbl
table.district.delimiter=|
table.district.primary-keys=d_w_id,d_id
table.district.schema=d_id:int,d_w_id:int,d_name:string,d_street_1:string,d_street_2:string,d_city:string,d_state:string,d_zip:string,d_tax:float,d_ytd:float,d_next_o_id:int,freshness_ts:timestamp

table.customer.file=CUSTOMER.tbl
table.customer.delimiter=|
table.customer.primary-keys=c_w_id,c_d_id,c_id
table.customer.schema=c_id:int,c_d_id:int,c_w_id:int,c_first:string,c_middle:string,c_last:string,c_street_1:string,c_street_2:string,c_city:string,c_state:string,c_zip:string,c_phone:string,c_since:timestamp,c_credit:string,c_credit_lim:float,c_discount:float,c_balance:float,c_ytd_payment:float,c_payment_cnt:int,c_delivery_cnt:int,c_data:string,c_n_nationkey:int,freshness_ts:timestamp

table.history.file=HISTORY.tbl
table.history.delimiter=|
table.history.primary-keys=h_c_id,h_c_d_id,h_c_w_id,h_d_id,h_w_id,h_date
table.history.schema=h_c_id:int,h_c_d_id:int,h_c_w_id:int,h_d_id:int,h_w_id:int,h_date:timestamp,h_amount:float,h_data:string,freshness_ts:timestamp

table.neworder.file=NEWORDER.tbl
table.neworder.delimiter=|
table.neworder.primary-keys=no_w_id,no_d_id,no_o_id
table.neworder.schema=no_o_id:int,no_d_id:int,no_w_id:int,freshness_ts:timestamp

table.order.file=ORDER.tbl
table.order.delimiter=|
table.order.primary-keys=o_w_id,o_d_id,o_id
table.order.schema=o_id:int,o_d_id:int,o_w_id:int,o_c_id:int,o_entry_d:timestamp,o_carrier_id:int,o_ol_cnt:int,o_all_local:int,freshness_ts:timestamp

table.orderline.file=ORDERLINE.tbl
table.orderline.delimiter=|
table.orderline.primary-keys=ol_w_id,ol_d_id,ol_o_id,ol_number
table.orderline.schema=ol_o_id:int,ol_d_id:int,ol_w_id:int,ol_number:int,ol_i_id:int,ol_supply_w_id:int,ol_delivery_d:timestamp,ol_quantity:int,ol_amount:float,ol_dist_info:string,freshness_ts:timestamp

table.item.file=ITEM.tbl
table.item.delimiter=|
table.item.primary-keys=i_id
table.item.schema=i_id:int,i_im_id:int,i_name:string,i_price:float,i_data:string,freshness_ts:timestamp

table.stock.file=STOCK.tbl
table.stock.delimiter=|
table.stock.primary-keys=s_w_id,s_i_id
table.stock.schema=s_i_id:int,s_w_id:int,s_quantity:int,s_dist_01:string,s_dist_02:string,s_dist_03:string,s_dist_04:string,s_dist_05:string,s_dist_06:string,s_dist_07:string,s_dist_08:string,s_dist_09:string,s_dist_10:string,s_ytd:int,s_order_cnt:int,s_remote_cnt:int,s_data:string,s_su_suppkey:int,freshness_ts:timestamp

table.nation.file=NATION.tbl
table.nation.delimiter=|
table.nation.primary-keys=n_nationkey
table.nation.schema=n_nationkey:int,n_name:string,n_regionkey:int,n_comment:string,freshness_ts:timestamp

table.supplier.file=SUPPLIER.tbl
table.supplier.delimiter=|
table.supplier.primary-keys=su_suppkey
table.supplier.schema=su_suppkey:int,su_name:string,su_address:string,su_nationkey:int,su_phone:string,su_acctbal:float,su_comment:string,freshness_ts:timestamp

table.region.file=REGION.tbl
table.region.delimiter=|
table.region.primary-keys=r_regionkey
table.region.schema=r_regionkey:int,r_name:string,r_comment:string,freshness_ts:timestamp
