tables=customer,company,savingaccount,checkingaccount,transfer,checking,loanapps,loantrans

table.customer.file=customer.csv
table.customer.delimiter=,
table.customer.primary-keys=custID
table.customer.schema=custID:int,companyID:int,gender:string,name:string,age:int,phone:string,province:string,city:string,loan_balance:float,saving_credit:int,checking_credit:int,loan_credit:int,Isblocked:int,created_date:date,last_update_timestamp:timestamp,freshness_ts:timestamp

table.company.file=company.csv
table.company.delimiter=,
table.company.primary-keys=companyID
table.company.schema=companyID:int,name:string,category:string,staff_size:int,loan_balance:float,phone:string,province:string,city:string,saving_credit:int,checking_credit:int,loan_credit:int,Isblocked:int,created_date:date,last_update_timestamp:timestamp,freshness_ts:timestamp

table.savingaccount.file=savingAccount.csv
table.savingaccount.delimiter=,
table.savingaccount.primary-keys=accountID
table.savingaccount.schema=accountID:int,userID:int,balance:float,Isblocked:int,ts:timestamp,freshness_ts:timestamp

table.checkingaccount.file=checkingAccount.csv
table.checkingaccount.delimiter=,
table.checkingaccount.primary-keys=accountID
table.checkingaccount.schema=accountID:int,userID:int,balance:float,Isblocked:int,ts:timestamp,freshness_ts:timestamp

table.transfer.file=transfer.csv
table.transfer.delimiter=,
table.transfer.primary-keys=id
table.transfer.schema=id:long,sourceID:int,targetID:int,amount:float,type:string,ts:timestamp,freshness_ts:timestamp

table.checking.file=checking.csv
table.checking.delimiter=,
table.checking.primary-keys=id
table.checking.schema=id:int,sourceID:int,targetID:int,amount:float,type:string,ts:timestamp,freshness_ts:timestamp

table.loanapps.file=loanApps.csv
table.loanapps.delimiter=,
table.loanapps.primary-keys=id
table.loanapps.schema=id:int,applicantID:int,amount:float,duration:int,status:string,ts:timestamp,freshness_ts:timestamp

table.loantrans.file=loanTrans.csv
table.loantrans.delimiter=,
table.loantrans.primary-keys=id
table.loantrans.schema=id:int,applicantID:int,appID:int,amount:float,status:string,ts:timestamp,duration:int,contract_timestamp:timestamp,delinquency:int,freshness_ts:timestamp
